var rule = {
  title: '宝石电影',
  host: 'https://www.baoshi3.cc/',
  url: '/show/fyclass--------fypage---.html',
  searchUrl: '/search/-------------.html?wd=**&submit=',
  searchable: 2,
  quickSearch: 0,
  filterable: 0,
  filter: '',
  filter_url: '',
  filter_def: {},
  headers: {
    'User-Agent': 'PC_UA',
  },
  timeout: 5000,
  class_name:'动作片&科幻片&恐怖片&喜剧片&爱情片&国产剧&动漫',
  class_url:'6&9&10&7&22&13&20',
  //class_parse: '.menu&&li:lt(7);a&&Text;a&&href;.*/(\\d+).html',
  cate_exclude: '',
  play_parse: true,
  limit: 6,
  lazy: "",
  double: true,
  推荐: '.lg-16;a&&title;img&&data-original;.team-state&&Text;a&&href',
  一级: '.lg-16;a&&title;img&&data-original;.team-state&&Text;a&&href',
  二级: {
    title: 'v.team-con&&title',
    img: '.team-img&&src',
    desc: '主要信息;.team-list&&p:eq(4)&&Text;.team-list&&p:eq(5)&&Text;.team-list&&p:eq(2)&&Text;.team-list&&p:eq(1)&&Text',
    content: '.plot-text&&Text',
    tabs: '.team-player&&ul&&li',
    lists: '.playlist:eq(#id)&&a',
    tab_text: 'body&&Text',
    list_text: 'body&&Text',
    list_url: 'a&&href',
  },
  搜索: '.lg-16;a&&title;img&&data-original;.team-state&&Text;a&&href',
}