var rule = {
  title: '河马短剧',
  host: 'https://www.kuaikaw.cn/',
  url: 'https://www.kuaikaw.cn/browse/fyclass/fypage',
  searchUrl: '/search/fypage?searchValue=**',
  searchable: 2,
  quickSearch: 0,
  filterable: 0,
  filter: '',
  filter_url: '',
  filter_def: {},
  headers: {
    'User-Agent': 'PC_UA',
  },
  timeout: 5000,
  class_name:'玄幻&穿越&奇幻&神豪&霸道总裁&强者回归&马甲',
  class_url:'720&718&715&475&1147&476&719',
  //class_parse: '.menu&&li:lt(7);a&&Text;a&&href;.*/(\\d+).html',
  cate_exclude: '',
  play_parse: true,
  limit: 6,
  lazy: "",
  double: true,
  推荐: '.FeaturedList_featuredItem__w9Jy0;img&&alt;img&&src;.FeaturedList_lastChapter__XbMSI&&Text;a&&href',
  一级: '.BrowseList_listItem__h7lD4;img&&alt;img&&src;.BrowseList_lastChapter__dkL54&&Text;a&&href;.BrowseList_bookIntro__x_w0W&&Text',
  二级: {
    title: '.wapBreadcrumb_lastTxt__F80VF&&Text',
    img: '.DramaDetail_bookCover__mvLQU&&src',
    desc: '主要信息;.team-list&&p:eq(4)&&Text;.team-list&&p:eq(5)&&Text;.team-list&&p:eq(2)&&Text;.team-list&&p:eq(1)&&Text',
    content: '.adm-ellipsis&&Text',
    tabs: '.dramaDetail_titleText__ykfQT',
    lists: '.dramaDetail_catalogItem__6OjPZ',
    tab_text: 'h3&&Text',
    list_text: 'a&&Text',
    list_url: 'a&&href',
  },
  搜索: '.MTagBookList_tagBookItem__C_038;img&&alt;img&&src;.MTagBookList_totalChapterNum__vjOW4&&Text;a&&href;.MTagBookList_intro__AN36F&&Text',
}