var rule = {
  title: '美柏影视',
  host: 'https://www.c494.com',
  url: '/dy/fyclass-fypage.html',
  searchUrl: '',
  searchable: 2,
  quickSearch: 0,
  filterable: 0,
  filter: '',
  filter_url: '',
  filter_def: {},
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  timeout: 5000,
  //class_parse: '.ui-nav&&li:lt(8);a&&Text;a&&href;.*/(\\d+).html',
  class_name:'电影&电视剧&综艺&动漫&短剧&体育赛事',
  class_url:'hd79&hd38&hd40&hd90&hd97&hd98',
  cate_exclude: '',
  play_parse: true,
  lazy: "js:\n  input = { parse: 1, url: input, js: '' };",
  double: true,
  推荐: '.img-list&&li;a&&title;img&&src;i&&Text;a&&href',
  一级: '.img-list&&li;a&&title;img&&src;i&&Text;a&&href',
  二级:{
    title: '.detail-title&&Text;.info&&dl:eq(7)&&Text',
    img: '.detail-pic&&img&&src',
    desc: '.info&&dl:eq(5)&&Text;.info&&dl:eq(6)&&Text;.info&&dl:eq(4)&&Text;.info&&dl:eq(0)&&Text;.info&&dl:eq(2)&&Text',
    content: '.tjuqing&&Text',
    tabs: '.down-title:lt(3)',
    lists: '.video_list:eq(#id)&&a',
    tab_text: 'body&&Text',
    list_text: 'body&&Text',
    list_url: 'a&&href',
  },
  搜索: '列表;标题;图片;描述;链接;详情',
}